stages:
  - test
  - report

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: cypress/included:13.17.0
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
      - cypress/reports/

report:
  stage: report
  image: node:16
  dependencies:
    - test
  script:
    - npm install
    - npx mochawesome-merge cypress/reports/*.json > cypress/reports/mochawesome.json
    - npx mochawesome-report-generator cypress/reports/mochawesome.json --inline
  artifacts:
    paths:
      - cypress/reports/mochawesome-report/
