stages:
  - install
  - test
  - deploy

variables:
  CYPRESS_INSTALL_BINARY: 0
  REPORT_DIR: "cypress/reports"

before_script:
  - npm ci

install:
  stage: install
  script:
    - echo "Instalando dependências..."

test:
  stage: test
  script:
    - npx cypress run --reporter mochawesome --reporter-options "reportDir=${REPORT_DIR},reporterFilename='[status]_[datetime]-[name]-reports',charts=true"
  artifacts:
    paths:
      - cypress/reports/*.html
      - cypress/reports/*.json
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - echo "Deploy do projeto"
  only:
    - master
