image: cypress/base:16.17.0

stages:
  - test

cache:
  paths:
    - node_modules/

variables:
  CI: true

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test
    - npm run merge-reports
    - npm run generate-report
  artifacts:
    when: always
    paths:
      - cypress/reports/mochawesome.html
      - cypress/reports/mochawesome.json
    expire_in: 1 week
  only:
    - main
