stages:
  - install
  - test

cache:
  paths:
    - node_modules/

variables:
  GIT_SSL_NO_VERIFY: "true"

install-dependencies:
  stage: install
  image: node:16
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  image: cypress/included:13.17.0
  script:
    - npm run test
  artifacts:
    when: always
    expire_in: 1 week
  allow_failure: false