# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Sauce_Demo-DB Continuos Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Start the server
      run: npm start &

    - name: Run Cypress tests
      run: npx cypress run --browser chrome

    - name: Upload Cypress test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-reports
        path: cypress/reports

    - name: Notify on failure
      if: failure()
      run: |
        echo "Tests failed. Sending notification..."
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Cypress tests failed!"}' https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL